name: my-first-workflow

on:
  push: 
   branches: 
     - main
  pull_request:
    branches:
      - main
    
  
 
  
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single Command in Job1
        run: echo "Hi This is my first Github workflow"

      - name: Checking os Release for GitHub Hosted Runner
        run: cat /etc/os-release
      -  name:  Calling Sleep
         run: sleep 20

  job2:
    name: JOB2
    runs-on: ubuntu-latest

    steps:
      - name: Checking the Hostname for Runner
        run: hostname

      - name: Running multiple commands
        run: |
          echo "Hi from kulbhushan mayer"
          echo "Current time is $(date)"
          sleep 20
  
  job3:
    name: JOB3
    needs: job1
    runs-on: windows-latest
    
    steps: 
      - name: job with Single Dependency
        run: sleep 10
      - name: Checking Runner Info
        run: get-computerinfo
        

  job4:
    name: Job4
    needs: [job1, job2, job3]
    runs-on: macos-latest
    
    steps:
    - name: Job for multiple dependencies
      run: sleep 10
    - name: Checking Runner Info
      run: sw_vers
      
     


    
    
