name: my-first-workflow

on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single Command in Job1
        run: echo "Hi This is my first Github workflow"

      - name: Checking os Release for GitHub Hosted Runner
        run: cat /etc/os-release
      -  name:  Calling Sleep
         run: sleep 20
      

     job2:
      name:  JOB2
      runs-on:  ubuntu-latest

      steps:
      -  name:  Checking the Hostanme for Runner
         run: Hostanme
      -  name:  Running multiple commands
         run: |
          echo " Hi from kulbhushan mayer"
          echo "Current time is `date`"
          sleep 20
  
    
